### ISSUE TITLE
Fix UI things according to feedback from Spencer / Brandon / Wells / Roadmap

### ISSUE THREAD

**Issue by thailandmatt** [byuoitav/team#863]
Blueberry
- [x] Z-pattern opacity fix
- [x] Z-pattern on help
- [x] dialogs don't auto close on click out
- [x] Help dialog - color / text
- [x] Power off all dialog
- [x] Share dialog
- [x] Mirroring dialog
- [x] Move Mixer Button
- [x] Mixer Dialog - color / text / tabs
- [x] Mixer Dialog - master volume on all
- [x] Master Volume Label
- [x] Volume slider size / button size
- [x] Volume slider touch when muted and unmute as well as change
- [x] Mix level for microphones / Master volume affecting them
- [x] Mix-mute flag instead of == 0 
- [x] Get rid of all SWAL dialogs and replace with new color / text

Cherry
- [x] Z-pattern opacity fix
- [x] Z-pattern on help
- [x] dialogs don't auto close on click out
- [x] Master Volume Label - master display
- [x] Volume slider size / button size
- [x] Volume slider touch when muted and unmute as well as change
- [x] Mix level for microphones
- [x] Mix-mute flag instead of == 0
- [x] Paging on the microphones and other audio devices

**Comment by jpw547** [comment]
- Mute master display volume
 - All sound from audio devices is muted.
 - All audio devices will not show the "Unmute" option unless that was previously set
 - Changing the level on the master display volume should unmute the master display volume
   - Setting the volume level to 0 should not mute
   - Muting and unmuting should not change the status of any audio device's "mixmute" property
- Mute mix level on an audio device
 - Muting the mix level on an audio device should mute the sound on that device. If the master is muted then it should still not be outputting sound
 - Changing the level on the mix level should unmute the mix level
   - Setting the mix level to 0 should not mute
- Mute mix level on an independent audio device
 - Muting the mix level on an independent audio device should mute the sound on that device. The master mute should not affect the independent audio devices in any way.
 - Changing the level on the mix level should unmute the mix level
   - Setting the mix level to 0 should not mute
